const projects = [
  {
    id: 'algorithmic-trading-system',
    name: 'Algorithmic Trading System',
    description: 'Built Python data pipeline to scrape and process terabytes of financial data using chunking, keyword extraction and NLP; automated collection of intraday stock data at 5-minute intervals. Engineered features and trained regression/classification models to generate trading signals using technical indicators, sentiment, and news velocity; developed backtesting framework for strategy validation.',
    techStack: ['Python', 'NLP', 'Machine Learning', 'Data Engineering'],
    githubLink: '',
    demoLink: '',
    dates: 'November 2025 – Present',
  },
  {
    id: 'mapreduce-framework',
    name: 'MapReduce Framework',
    description: 'Developed a multi-threaded, distributed MapReduce framework in Python with fault-tolerant job scheduling, TCP/UDP socket communication, and multi-threaded task coordination across worker nodes.',
    techStack: ['Python', 'Distributed Systems', 'Networking', 'Multi-threading'],
    githubLink: '',
    demoLink: '',
    dates: 'October 2025 – November 2025',
  },
  {
    id: 'projectverse',
    name: 'ProjectVerse',
    description: 'Built a social platform for developers to showcase projects and generate custom portfolios. Scaled to 2,000+ visitors, 200+ registered users, and dozens of user-submitted projects. Implemented frontend with React and backend with Express.js and PostgreSQL.',
    techStack: ['React', 'Express.js', 'PostgreSQL', 'JavaScript', 'HTML/CSS'],
    githubLink: '',
    demoLink: 'https://www.projectverse.dev/',
    dates: 'May 2025 – July 2025',
  },
  {
    id: 'code-collab',
    name: 'Code Collab',
    description: 'Built a real-time, multi-user code IDE with React, Node/Express, and Socket.IO. Integrated Monaco Editor with syntax highlighting, enabled code persistence using Redis, and containerized the application with Docker.',
    techStack: ['React', 'Node.js', 'Express.js', 'Socket.IO', 'Redis', 'Docker', 'Monaco Editor'],
    githubLink: 'https://github.com/aayushsh06/code-collab',
    demoLink: 'https://codecollabio.onrender.com/',
    dates: 'April 2025 – May 2025',
  },
  {
    id: 'algoscope',
    name: 'AlgoScope',
    description: 'Deployed an interactive web application using JavaScript and React to visualize the real-time traversal of various pathfinding algorithms on a user-customizable grid. Additional features include maze generation using a randomized DFS implementation, randomized node weight generation, and algorithm performance statistics.',
    techStack: ['JavaScript', 'React', 'HTML/CSS'],
    githubLink: 'https://github.com/aayushsh06/AlgoScope',
    demoLink: 'https://aayushsh06.github.io/AlgoScope/',
    dates: 'March 2025 – May 2025',
  },
  {
    id: 'custom-query-language',
    name: 'Custom Query Language',
    description: 'Developed a SQL-like query language in C++ supporting core relational algebra operations such as SELECT and JOIN, with indexing implemented using Binary Search Trees and hashing for performance optimization. Built a custom parser and interpreter to process and execute user queries. Implemented custom in-memory data structures, improving performance by up to 20% in benchmark tests.',
    techStack: ['C++', 'Data Structures', 'Algorithms', 'Parser Design'],
    githubLink: '',
    demoLink: '',
    dates: 'March 2025 – April 2025',
  },
  {
    id: 'python-data-analysis',
    name: 'Python Data Analysis',
    description: 'Developed a RandomForestRegressor in Python and Scikit-learn to predict recipe outcomes, reducing validation MSE by 50% and test MSE by 15%. Performed univariate and bivariate analyses with visualizations to support research findings.',
    techStack: ['Python', 'Scikit-learn', 'Data Analysis', 'Machine Learning'],
    githubLink: '',
    demoLink: 'https://aayushsh06.github.io/recipe-analysis/',
    dates: 'February 2025 – April 2025',
  },
  {
    id: 'maize-market',
    name: 'Maize Market',
    description: 'Developed a full-stack online marketplace and real-time chat application for UMich students, featuring student authentication, product listing, cart functionality, and a chat system for transaction communication. Utilizing Java, Spring Boot, and PostgreSQL for backend and React and Javascript for frontend.',
    techStack: ['Java', 'Spring Boot', 'JavaScript', 'React', 'HTML/CSS', 'PostgreSQL'],
    githubLink: 'https://github.com/aayushsh06/Maize-Market',
    demoLink: '',
    dates: 'November 2024 – May 2025',
  },
  {
    id: 'text-to-ai',
    name: 'Text-to-AI',
    description: 'Developed an AI-powered short-form video generator with script, voice, and subtitle synchronization, producing 50+ videos. Built a custom captioning algorithm with 90%+ accuracy, a Flask backend, and an HTML/CSS and JS frontend, gaining experience with RESTful APIs and Git.',
    techStack: ['Python', 'Flask', 'JavaScript', 'HTML/CSS'],
    githubLink: 'https://github.com/aayushsh06/Text-to-AI',
    demoLink: '',
    dates: 'November 2024 – December 2024',
  },
  {
    id: 'diffnosis',
    name: 'Diffnosis',
    description: 'Developed a virtual health consultant app using Xcode and Swift, enabling users to perform differential diagnoses with medical data while integrating health risk assessments for travel from WHO and CDC. Implemented LLAMA 3.2 models for real-time diagnoses and image analysis of epidermal anomalies. Created backend functionalities in Python with Scrapy to scrape outbreak reports from WHO and CDC.',
    techStack: ['Swift', 'Python', 'Xcode', 'Scrapy', 'LLAMA 3.2'],
    githubLink: 'https://github.com/aayushsh06/Diffnosis',
    demoLink: '',
    dates: 'September 2024',
  },
  {
    id: 'discord-server-bot',
    name: 'Back-End Bot Development',
    description: 'Deployed several Discord bots in servers with ~50 users, including an AI Chatbot and Calendar Bot, integrating the GPT-4 API and scheduling features using Javascript and Node.js/Discord.js.',
    techStack: ['JavaScript', 'Node.js', 'Discord.js', 'GPT-4 API'],
    githubLink: 'https://github.com/aayushsh06/Discord-Bots',
    demoLink: '',
    dates: 'May 2024 – August 2024',
  },
  {
    id: 'e-recycle-now',
    name: 'E-Recycle Now',
    description: 'Designed a mobile app for e-waste recycling, leveraging Java with ML-powered item scanning and disposal guidance, earning First Runner-Up in the Congressional App Challenge. Utilized TensorFlow, SQLite, Android Studio, and Google Maps API for functionality and integration.',
    techStack: ['Java', 'Android Studio', 'SQLite', 'TensorFlow', 'Google Maps API'],
    githubLink: 'https://github.com/aayushsh06/E-Recycle-Now',
    demoLink: '',
    dates: 'June 2022 – November 2022',
  },
  {
    id: 'ncaa-predictive-modeling',
    name: 'Predictive Modeling of NCAA Final Four Outcomes',
    description: 'Implemented and assessed k-NN, SVM, Decision Tree, and Logistic Regression models on basketball data to predict Final Four outcomes, optimizing for accuracy, F1-score, and Jaccard index. Delivered predictions with ~20% greater accuracy than traditionally favored odds, demonstrating superior model performance in a complex, multi-variable environment.',
    techStack: ['Python', 'Machine Learning', 'Scikit-learn', 'Data Analysis'],
    githubLink: '',
    demoLink: '',
    dates: 'April 2021 – June 2021',
  },
];

export default projects;
